---
title: "Sugestões de melhorias e comentários"
subtitle: "MEDIDAS DE DIAGNÓSTICO EM MODELOS DE REGRESSÃO BETA PRIME"
date: "23/08/2023 as 14h00"
lang: pt
author: "Prof. Dr. Pedro Rafael D. Marinho"
format: html
code-tools: true
code-copy: true
number-sections: true
page-layout: full
editor: source
---

# Objetivos principais e observações:

Os objetivos principais do trabalho são:

1. Estudo dos resíduos do modelo de regressão beta prime, para além do que Bourguignon et al. (2021) considerou.

2. Bourguignon et al. (2021) considerou os resíduo quantílico e do de Pearson;

3. Aqui foram considerados os resíduo:
  + resíduos ponderado;
  + **ponderado padronizado**. Esse foi o resíduo proposto;
  + Pearson padronizado;
  + Foi proposto coeficiente de predição $P^2$.

4. Avalia-se a distribuição empírica dos
resíduos em diferentes cenários do modelo de regressão BP e comparamos seus desempenhos
para detectar especificação incorreta.

5. A distribuição beta prime pode ser escrita na família exponencial de distribuições. Portanto, "compete" com os modelos lineares generalizados.

7. Densidade da Beta Prime


$$f(y;\alpha, \beta) = \frac{y^{\alpha - 1}(1 + y)^{-(\alpha + \beta)}}{B(\alpha, \beta)}, y \geq 0,$$
com $\alpha > 0$ e  $\beta > 0$.

8. Notações:

+ $r_i^Q$: resíduo quantílico;
+ $r_i^P$: resíduo de Pearson;
+ $r^{\beta}$: resíduo poderado;
+ $r^{\beta*}$: resíduo ponderado padronizado;
+ $r^{P *}$: resíduo de Pearson padronizado.

# Seguestões e comentários

## O que é definir os resíduos ponderado e Pearson padronizado?

No resumo você diz: 

> "além do resíduo quantílico e do
resíduo de Pearson utilizados por Bourguignon et al. (2021), **definimos** os resíduos ponderado,
ponderado padronizado (ESPINHEIRA et al., 2008) e Pearson padronizado (MCCULLAGH;
NELDER, 1989) para tal modelo." -- Maria Eduarda

O que é definir os resíudos? Não seria melhor trocar definir por "avaliamos"? Eles não já foram definidos pelos autores de uma forma genérica? Definir tem conotação de que vocês criaram.

## Suporte da distribuição BP

O suporte da distribuição da beta prime não inclue o zero ($y \geq 0$)? Sei que Bourguignon et al. (2021) definiu como $y > 0$, mas não seria $y \geq 0$? Note que na página 34 do paper (página 2 do PDF), último parágrafo, ele diz:

> Pode-se provar que a função densidade BP está diminuindo com $f(y|\alpha,\beta)$, se $0 < \alpha < 1$ com moda em $y = 0$. - Bourguignon et al. (2021)

Além disso, nas referências da distribuição $y\geq 0$.

**Uma observação**: Ela também é conhecida como distribuição de Pearson tipo VI. 🎁

<!-- ## Estudar se a distribuição normal é uma boa aproximação? -->

<!-- No trabalho vocês estudam se a distribuição normal-padrão é uma boa aproximação para os resíduos.  -->

<!-- > "Em particular, objetivamos verificar se a distribuição normal -->
<!-- padrão é uma boa aproximação para a distribuição empírica desses cinco resíduos, quando o -->
<!-- modelo de regressão BP é corretamente especificado, e analisar seus desempenhos para detectar -->
<!-- erros de especificação." -- Maria Eduarda -->

<!-- Isso já não seria esperado pelo Teorema Central do Limite - TCL? Se eu tenho uma sequência de variáveis aleatórias i.i.d's, não é esperado se tenho dados suficientes, terei uma boa aproximação? Por que simular isso se eu tenho garantias teóricas da boa aproximação? -->


## Utilizar a teoria da informação

A ideia do estudo é a avaliação dos resíduos para a análise da especificação do modelo de regressão beta prime. Portanto, queremos estimar $r({\bf x}) = \mathbb{E}(Y|X)$, ou seja, desejamos uma função de regressão com boa capacidade preditiva. Uma das suposiões é que $Y\sim BP$. 

Pergunta: em cenários em que $Y$ segue a distribuição aproximadamente BP, utilizar estatísticas de adequação de ajuste para comparar a regressão BP com outros modelos de regressão, a exemplo, dos MGL's, como, por exemplo, com o modelo MLG com $Y \sim Gama$, a análise de resíduos proposta não levam as mesmas conclusões de que chegaríamos em aplicar utilizar a teoria da informação para checar a qualidade do ajuste? Por exemplo, utilizar estatísticas como a estatística de Cramér-von Mises e Anderson-Darling para modelos não encaixados não poderia ser útil para comparar a distribuição de $Y$ e decidir qual modelo melhor se ajusta aos dados? 

## Especificação correta garante boa capacidade preditiva?

A especificação adequada do modelo garante boa capacidade preditiva? No resumo você diz:

> "Para isso, é importante utilizar resíduos com propriedades
conhecidas e que apresentem bom desempenho." - Maria Eduarda


Segundo a lógica de aprendizagem de máquina não! Ver o paper do Leio Breiman:

> [Breiman, L. (2001a). Statistical modeling: The two cultures. Statistical Science, 16(3), 199–231](https://projecteuclid.org/journalArticle/Download?urlId=10.1214%2Fss%2F1009213726)

Nesse artigo ele estabelece duas culturas na modelagem estatística:

1. **Data modeling culture**: nela, em geral, se assume que o modelo de regressão utilizado $r({\bf x}) = \mathbb{E}(Y|{\bf X})$ é correto. O principal objetivo dessa abordagem é a interpretação dos parâmetros que indexam o modelo $r({\bf x})$.

2. **Algorithmic modeling culture**: essa é a cultura que domina a comunidade de aprendizagem de máquina. Nessa abordagem, o principal objetivo são as predições por meio de novas observações. Não se assume que o modelo utilizado é o modelo correto. Nesse tipo de modelagem, muitas vezes os algoritmos não envolve nenhuma estrutura probabilística. Muitas vezes, modelos não bem especificado conduzem a boas predições.

Existe uma sequência de respostas à esse paper, por exemplo, estatísticos renomados como o David Cox e o Bradley Efron respondem positivamente à esse paper. O artigo possui mais de 5300 citações.


Podemos ter modelos que não estão bem especificados, mas possuem boa performance preditiva. Por exemplo, tente ajustar um [random forest](https://hastie.su.domains/ISLR2/ISLRv2_corrected_June_2023.pdf) em um problema, mesmo $Y \in B(\alpha,\beta)$, em um grande conjunto de dados, e usando um conjunto de teste, calcule o erro quadrático médio observado na amostra independente. Muito provavelmente o *random forest* terá uma capacidade preditiva igual ou superior ao modelo de regressão BP.

Dessa forma, sugiro você comentar um pouco mais qual a grande importância da boa especificação do modelo. Essa boa especificação não está única e exclusivamente na capacidade preditiva do modelo, pois muitas vezes poderemos nos surpreender com modelos não muito bem especificado e que performa muito melhor. A grande contribuição de termos um modelo que esteja bem especificado é permitir que análises interpretativas possam ser realizadas. É preciso destacar isso, uma vez que muitas pessoas que estão lendo materiais da estatística são pessoas da ciência de dados/computação, em que muitas dalas "pregam" que o interesse está na previsão e ofuscam a importância de ter modelos bem especificados quando desejamos perceber a relação entre as variáveis, construir intervalos para os parâmetros e testar hipóteses.

No material fica um pouco nebuloso de qual a grande ideia de se fazer uma análise de resíduos.

## Avaliamos a distribuição empírica dos resíduos

Vocês fazem uma análise de distribuição empírica do resíduo, para detecção da especificação incorreta do modelo de regressão BP. Existe um apelo frequentista, uma vez que necessita-se de uma aproximação assintótica da distribuição dos resíduos para a normal. Até que ponto, essa análise é melhor que utilizar a teoria da informação e estudar a distribuição de $Y$, sobretudo em situações em que temos poucos dados ou uma quantidade moderada de dados?

## Pensam em adicionar penalização?

Sei que vocês focaram em desenvolver inferência para auxiliar a análise de especificação do modelo de regressão BP. Porém, vocês pensaram dar passos para avançar o modelo de regressão BP, por exemplo, pensam em adicionar algum tipo de penalização no modelo de regressão beta prime? Existe um *trade off* entre viés e variância, em que uma penalização poderia fazer com que o modelo viesse performar melhor. Um estudo avaliando a peformance do modelo com e sem penalização, em diversos cenários poderia ser interessante.

## A variância do modelo de regressão BP é maior? Como assim?

Você diz:

> "Uma das vantagens refere-se à modelagem de dados mais dispersos, uma vez que a variância do
modelo de regressão BP é maior que a variância do modelo gama." - Maria Eduarda, página 12

Você refere-se à variância do modelo ou a capacidade do modelo em modelar $Y$ com maior variância? O risco preditivo do modelo não sofre com modelos com maior variância? Veja que o risco preditivo $R(\widehat{g})$, usando a norma $L_2$ no risco preditivo de um modelo de regressão, temos que o risco poderá ser decomposto como:

$$R(\widehat{g}) = \mathbb{E}\left[(Y - \widehat{g}({\bf X}))^2| {\bf X} = {\bf x}\right] = \underbrace{\mathbb{V}[Y | {\bf X = x}]}_{\mathrm{i - Variância\,\, intrínseca}} + \overbrace{(r({\bf x}) - \mathbb{E}[\widehat{g}({\bf x})])^2}^{\mathrm{ii - Viés\, ao\, quadrado\, do\, modelo}} + \underbrace{\mathbb{V}[\widehat{g}({\bf x})]}_{\mathrm{iii - Variância\, do\, modelo}},$$ 

em que $\widehat{g}(\cdot)$ é sua função de regressão estimada. Quando você diz que a variância do modelo de regressão BP é maior, você não está dizendo que iii é maior? Isso não me daria um maior risco preditivo? Escreva melhor o que você está querendo dizer com variância maior!

Muito provavelmente existem diversas sequências de observações de $Y$ em que poderiam ser bem modeladas pela distribuição Gama e também pela distribuição BP. Se o modelo de regressão BP tem variância maior, poderia entender que modelar por um MLG eu teria um modelo que performa melhor? Como foi verificado que a variância do modelo é maior! Isso é realmente algo bom?

Você não estaria querendo dizer que o modelo de regressão BP modela dados mais dispersos? Isso pode ser diferente de um modelo com variância maior.


## O que é precisão dos dados?

> Por outro lado, o resíduo ponderado padronizado aqui proposto deverá ser
utilizado com cautela, dado que os experimentos de Monte Carlo revelaram que a proximidade
da sua distribuição empírica pela distribuição normal padrão depende da precisão dos dados
ajustados pelo modelo de regressão BP. - Maria Eduarda, página 41, primeira linha.

**Precisão dos dados? Essa expressão é estranha!**

O que tem que ser preciso são os modelos. Acho que você se refere à convergência assintótica das estimativas dos erros, nesse caso, do estimador do resíduo ponderado padronizado, denotado no trabalho por $r_i^{\beta^*}$ para a distribuição normal. Daí, quando $n \rightarrow +\infty$ temos que pela Teorema Central do Limite, $r_i^{\beta^*}$ deve convergir em distribuição para a distribuição normal. **Precisão de dados** tem outra conotação!

## Em qual situação $r_i^{\beta *}$ é melhor que $r_i^{Q}$

Em que situação os resíduos propostos (resíduo ponderado padronizado) é melhor que utilizar o $r_i^{Q}$? Ao fim, existe alguma situação que eu devo utilizar $r_i^{\beta *}$?

## Na avaliação das estatísticas PRESS

[PRESS - Soma dos Quadrados dos Erros de Previsão](https://sci-hub.se/https://www.tandfonline.com/doi/abs/10.1080/00401706.1974.10489157)

Para avaliar a capacidade preditiva do modelo, é preciso que a sequência de variáveis aleatórias $(Y_i - \widehat{Y}_i)^2$ sejam i.i.d's, de modo que se você utiliza a mesma amostra para ajustar o modelo e obter $\widehat{Y}$ também para avaliar $d_1^2 = (Y_1 - \widehat{Y}_1)^2, d_2^2 = (Y_2 - \widehat{Y}_2)^2, \cdots, d_m^2 = (Y_m - \widehat{Y}_m)^2$, fazem com que essa sequência não sejam independentes. É preciso ter $m$ novas observações que não foram utilizadas para ajustar o modelo. Não tendo independência, não há garantias da lei dos grandes números para que

$$PRESS \rightarrow \mathbb{E}[(Y - \widehat{Y})^2] = n \times EQM$$

Em outras palavras, se foram utilizados as mesmas observações para calcular $\widehat{y}_i$, para todo $i$, então a sequência $(y_i - \widehat{y}_i)^2$ não são observações de uma sequência de variáveis aleatórias independentes, e a aproximação acima não é verdadeira. Essa separação de um conjunto de novas observações é feita em todo procedimento de validação cruzada, como no caso mais geral que é o *leave-one-out cross-validation*. 

Muitas observações, a saber $n - 1$, são utilizadas para calcular $\widehat{y}_i$, para todo $i = 1, \cdots, n$. Portanto, existe dependência entre a sequência $d_1^2, \cdots, d_n^2$. O interessante seria considerar $m$ novas observações, e calcular $d_{n + 1}^2, \cdots, d_{m}^2$. É por isso, que muitos algoritmos de aprendizagem de máquina utilizam um conjunto de teste independente dos dados que são utilizados para ajustar os modelos.

## Página 47 $e_{(i)}$

Não seria melhor trocar $e_{(i)} = y_i - \widehat{y}_{(-i)}$ por $r_{(i)}$? O $e_{(i)}$ me induz a pensar no erro que é o que desejamos estimar.

## Ainda sobre a independência

O artigo do [Mediavilla](http://www.na-businesspress.com/JABE/MendezWeb.pdf) não é um paper com muitos cuidados. Não é verdade que a sequência de observações são independentes.

Na página 48 você diz:

> Como a $i$-ésima observação é omitida para prever $y_i$, então $\widehat{y}_{(-i)}$ e $e_{(-i)}$ são independentes, o que garante que a estatística $PRESS$ seja uma medida indicativa da capacidade de
previsão de um modelo de regressão, independentemente da qualidade do ajuste do modelo
(MEDIAVILLA et al., 2008).

Insisto que essa sequência não são de observações de variáveis aleatórias independentes. Clique [AQUI](https://pedro-rafael.shinyapps.io/shiny_apps/#section-avalia%C3%A7%C3%A3o-do-risco-preditivo) em que criei uma aplicação Web em que avalio o risco preditivo usando um precedimento de *leave-one-out cross-validation*, para uma regressão polinomial. Chamo de "certo" o risco quando avaliado em um conjunto de dados independente, em que nenhuma observação foi utilizada para calcular $\widehat{y}_i$ e chamo de "errado" o procedimento de realizar o *leave-one-out cross-validation* e depois não reavaliar o melhor modelo em um conjunto de dados independente. Note que, da forma errada, apenas selecionado o modelo usando*leave-one-out cross-validation* sem considerar um conjunto de teste me conduz a ideia de que aumentar o grau do polinômio, i.e., introduzir mais parâmetros sempre será uma boa altarnativa. Isso não é verdade, uma vez que um polinômio com grau muito elevado me leva à *overfitting*.

## AIC

Por que vocês não compararam a performance da adequação de ajuste do modelo usando o AIC? O procedimento de **Leave-one-out cross-validation** ao qual se baseia a estatística $PRESS$ (ver Allen 1974), em que

$$PRESS = \sum_{i = 1}^n (Y - \widehat{Y}_{(i)})^2.$$
Só que Stones, um pouco depois, em 1977, mostro que **Leave-one-out cross-validation** converge assintoticamente para o método AIC. Vocês possuem a estrutura probabilística do modelo que permite o cálculo analítico do AIC. Portanto, avaliar o risco preditivo usando o AIC já seria suficiente, i.e, seria o melhor resultado assintótico do **leave-one-out**. Leia o artigo [An Asymptotic Equivalence of Choice of Models by Cross-validation and Akaike's Criterion](https://www.jstor.org/stable/2984877). Esse paper é citado em mais de 1500 trabalhos.

Sugiro que seja comparado também com o AIC, uma vez que isso é facilmente feito.


## Como se comportam as estatísticas $P_{\beta}^2$ e $P_{\beta_c}^2$

Na página 49 você define as estatísticas $P_{\beta}^2$ e $P_{\beta_c}^2$. Como se comportam tais estatísticas na presença de mais covariáveis no modelo? São monótonas? Seria legal ter uma simulação de Monte-Carlo mostrando como se comportam tais estatísticas e se elas penalizam modelos com muitos parâmetros. Fazer um gráfico com a evolução das estatísticas em que no eixo $x$ você vai aumentando a quantidade de parâmetros seria uma forma boa de visualizar o comportamento. A ideia é que as estatísticas $P_{\beta}^2$ e $P_{\beta_c}^2$ decresçam e a partir de um momento começem a piorar na medida que aumenta-se a quantidade de covariáveis. 

Veja essa aplicação que implementei  a estatística $P^2$ para um modelo de regressão polinomial. Note que ela sinaliza que colocar mais parâmetros sempre é uma boa opção!

Clique [**AQUI**](https://pedro-rafael.shinyapps.io/shiny_apps/#section-maria-eduarda) para ver.

A estatística $P_{\beta_c}^2$ sofre com isso? Seria legal fazer um gráfico mostrando qual o comportamento dela quando se adiciona mais covariáveis no modelo.

## Cadê os demais códigos?

No código das simulações há diversas interções de códigos R com o a função `source()`. Onde estão esses arquivos. Sugiro criar uma conta no [GitHub](https://github.com/) e criar um repositório com o script R e um pequeno comentário do que cada código faz.

  + Onde está `gamlss_BP.R`?
  + Onde está `glmBP.R`?
  + Onde está `Estimation.R`?
  + Onde está `Residual_H_Log_Like_BP.R`?
  
Por exemplo, no paper do Marcelo, ele coloca a referência para o repositório do GitHub em que contém o pacote **BPmodel** ([ver aqui](https://github.com/santosneto/BPmodel)) que muito provavelmente você está usando em algum script. 
  
É preciso que seu experimento seja totalmente repoduzível. Quem ler quer chegar aos mesmos resultados!

## Por que `i <- i - 1`

No código, na página 88, dentro da instrução `else`, por que fazer `i <- i - 1`? Não há problema teórico, pois na verdade se terá mais réplicas que as 10 mil. Então, na verdade foram realizadas mais de 10 mil répicas de Monte-Carlo.

## Qual o método de otimiação usado em `gamlss`?

Qual o método de otimização utilizado pela função `gamlss`? Seria interessante colocar nas tabelas a taxa de não convergência. Isso é útil, uma vez que não há forma fechada para os estimadores de máxima verossimilhança. Perceber como a otimização numérica performa na maximização da função de log-verossimilhança é uma informação útil.